name: maniptrans
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - ansitable==0.11.4
      - antlr4-python3-runtime==4.9.3
      - anyio==4.5.2
      - arm-pytorch-utilities==0.4.3
      - asttokens==3.0.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - avp-stream==1.0
      - backcall==0.2.0
      - black==24.8.0
      - blinker==1.8.2
      - bps-torch==0.1
      - cachetools==5.5.2
      - casadi==3.6.6
      - certifi==2025.10.5
      - cfgv==3.4.0
      - chamfer-distance==0.1
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.1.8
      - cloudpickle==3.1.1
      - coacd==1.0.5
      - colored==1.4.4
      - colorlog==6.8.2
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - dash==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.3.9
      - distlib==0.4.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - easydict==1.13
      - einops==0.8.0
      - embreex==2.17.7.post5
      - etils==1.3.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.57.0
      - frankx==0.2.0
      - freetype-py==2.5.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - grpcio-tools==1.48.2
      - gym==0.23.1
      - gym-notices==0.1.0
      - h11==0.16.0
      - h5py==3.11.0
      - httpcore==1.0.9
      - httpx==0.27.0
      - hydra-core==1.3.2
      - identify==2.6.1
      - idna==3.11
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lightning-utilities==0.11.9
      - llvmlite==0.41.1
      - loguru==0.7.2
      - lxml==6.0.2
      - manifold3d==2.5.1
      - manotorch==0.0.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mujoco==3.2.3
      - multidict==6.1.0
      - mypy-extensions==1.1.0
      - narwhals==1.42.1
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==2.2
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.58.1
      - numpy==1.23.5
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pgraph-python==0.6.3
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pip==24.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==6.3.1
      - portalocker==3.0.0
      - pre-commit==3.5.0
      - progress==1.6.1
      - promise==2.3
      - prompt-toolkit==3.0.52
      - propcache==0.2.0
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybullet==3.2.6
      - pycollada==0.6
      - pygame==2.1.0
      - pyglet==2.1.9
      - pygments==2.19.2
      - pymeshlab==2023.12.post2
      - pyopengl==3.1.0
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytorch-kinematics==0.7.2
      - pytorch-lightning==2.2.5
      - pytorch-seed==0.2.0
      - pytorch3d==0.7.3
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.35.1
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - retrying==1.4.2
      - rl-games==1.6.1
      - roboticstoolbox-python==1.1.1
      - rpds-py==0.20.1
      - rsa==4.9.1
      - rtb-data==1.0.1
      - rtree==1.3.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - shapely==2.0.5
      - shortuuid==1.0.13
      - simanneal==0.5.0
      - six==1.17.0
      - smmap==5.0.2
      - smplx==0.1.28
      - sniffio==1.3.1
      - spatialgeometry==1.1.0
      - spatialmath-python==1.1.14
      - stack-data==0.6.3
      - svg-path==6.3
      - swift-sim==1.1.0
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tomli==2.3.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchgeometry==0.1.2
      - torchmetrics==1.5.2
      - torchvision==0.14.1+cu117
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.9.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urdf-parser-py==0.0.4
      - urdfpy==0.0.22
      - urllib3==2.2.3
      - vhacdx==0.0.8.post1
      - virtualenv==20.35.3
      - wandb==0.12.21
      - wcwidth==0.2.14
      - websockets==13.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - xatlas==0.0.9
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.15.2
      - yourdfpy==0.0.56
      - zipp==3.20.2
prefix: /home/cyrus/miniconda3/envs/maniptrans
